; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppNameDefault "LK Next"
#define MyAppVersion "1.1.0-alpha"
#define MyAppPublisher "LocalizedKorabli"
#define MyAppURL "https://github.com/LocalizedKorabli"
#define MyAppExeName "lki.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A6DC98F1-CF0D-4AAC-9B23-C6D81DD4B123}
AppName={cm:MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
WizardImageFile=..\assets\wizard.bmp
WizardSmallImageFile=..\assets\wizard_small.bmp
DisableWelcomePage=no
DefaultDirName={autopf}\LocalizedKorabli\LKInstallerNext
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
OutputBaseFilename="lki_setup"
SetupIconFile=..\resources\logo\logo.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
UsePreviousAppDir=no
UsePreviousLanguage=no
VersionInfoDescription={#MyAppNameDefault}
VersionInfoProductName={#MyAppNameDefault}
PrivilegesRequired=admin
SignTool=mysign
SignedUninstaller=yes

[Files]
Source: "..\dist\lki.dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Languages]
Name: "zh_CN"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"; InfoBeforeFile: "..\assets\welcome_chs.txt"; LicenseFile: "..\assets\license.txt";
Name: "zh_TW"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"; InfoBeforeFile: "..\assets\welcome_cht.txt"; LicenseFile: "..\assets\license.txt";
Name: "en"; MessagesFile: "compiler:Default.isl"; InfoBeforeFile: "..\assets\welcome_en.txt"; LicenseFile: "..\assets\license.txt";
Name: "ru"; MessagesFile: "compiler:Languages\Russian.isl"; InfoBeforeFile: "..\assets\welcome_ru.txt"; LicenseFile: "..\assets\license.txt";
Name: "ja"; MessagesFile: "compiler:Languages\Japanese.isl"; InfoBeforeFile: "..\assets\welcome_ja.txt"; LicenseFile: "..\assets\license.txt";

[CustomMessages]
zh_CN.MyAppName=澪刻 Next: Mir Korabley 本地化安装器
zh_TW.MyAppName=澪刻 Next: Mir Korabley 在地化安裝器
en.MyAppName=LK Next: Mir Korabley L10n Installer
ru.MyAppName=LK Next: Установщик локализации «Мира кораблей»
ja.MyAppName=澪刻 Next: Mir Korabley オンライン自動インストーラー

[Registry]
Root: HKLM; Subkey: "Software\LocalizedKorabli\LKInstallerNext"; ValueType: string; ValueName: "InstallLanguage"; ValueData: "{language}"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\LKNext.exe"; ValueType: string; ValueName: ""; ValueData: "{app}\lki.exe"; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\LKNext.exe"; ValueType: string; ValueName: "Path"; ValueData: "{app}"; Flags: uninsdeletekey

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Icons]
Name: "{autoprograms}\{cm:MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{cm:MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{cm:MyAppName}}"; Flags: nowait postinstall shellexec

